# Generated by Django 5.1 on 2024-09-03 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
            ],
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'Артист', 'verbose_name_plural': 'Артисты'},
        ),
        migrations.RemoveField(
            model_name='artist',
            name='surname',
        ),
        migrations.AddField(
            model_name='artist',
            name='show_name',
            field=models.TextField(default=1, verbose_name='Название номера'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.TextField(verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='artist',
            name='show',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artists.show'),
        ),
    ]
