# Generated by Django 5.1 on 2024-09-04 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_show_alter_artist_options_remove_artist_surname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'verbose_name': 'Номер', 'verbose_name_plural': 'Номера'},
        ),
        migrations.RemoveField(
            model_name='artist',
            name='show_name',
        ),
    ]
