# Generated by Django 5.1 on 2024-09-10 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_alter_show_options_remove_artist_show_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_type', models.TextField(verbose_name='Тип шоу')),
            ],
            options={
                'verbose_name': 'Тип шоу',
                'verbose_name_plural': 'Типы шоу',
            },
        ),
        migrations.AddField(
            model_name='show',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artists.type'),
        ),
    ]
