# Generated by Django 5.1 on 2024-09-10 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_type_show_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='price',
            field=models.IntegerField(default=1, verbose_name='Стоимость'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('place', models.TextField(verbose_name='Место')),
                ('show', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artists.show')),
            ],
            options={
                'verbose_name': 'Доход',
                'verbose_name_plural': 'Доходы',
            },
        ),
    ]
