# Generated by Django 5.1 on 2024-10-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='picture',
            field=models.ImageField(null=True, upload_to='artists', verbose_name='Изображение'),
        ),
    ]
