# Generated by Django 5.1 on 2024-10-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0007_artist_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='picture',
            field=models.ImageField(null=True, upload_to='artists', verbose_name='Изображение'),
        ),
    ]
